---
title: "String practice"
format: html
editor: visual
---
```{r}
library(datapasta)
library(stringr)
library(tidyverse)

# create data frame
alarm_report <- data.frame(
  stringsAsFactors = FALSE,
              date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
          building = c("Engineering-North",
                       "Bren Hall","Engineering-South","Engr-North"),
     alarm_message = c("10:02am -- HVAC system down, facilities management alerted",
                       "8:24am -- Elevator North out of service",
                       "12:41am -- Fire alarm, UCSB fire responded and cleared",
                       "9:58pm -- Campus point emergency siren, UCPD responded")
)

```

```{r}
# practice with strings
alarm_report <- alarm_report %>%
  # replace Engr with Engineering
  mutate(building = str_replace(building, pattern = "Engr", replacement = "Engineering")) %>% 
  # separate building into two cols
  separate(building, into = c("building", "wing"), sep = "-") %>% 
  # keep observations with word "responded"
  filter(str_detect(alarm_message, pattern = "responded")) %>% 
  # separate message time from rest at --
  separate(alarm_message, into = c("time", "message"), sep = "--") %>% 
  # convert date column to Date class
  mutate(date = lubridate::ymd(date))
```

